mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path

from myapp.views import detail, index

app_name = 'myapp'

urlpatterns = [
    path('', index, name="home"),
    path('detail/<int:product_id>/', detail, name='detail')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self) -> str:
        return self.name

mysite/myapp/views.py
from django.shortcuts import render

from .models import Product



def index(request):

    products = Product.objects.all()

    context = {
        "products": products
    }
    return render(request, "myapp/index.html", context)

def detail(request, product_id):
    product = Product.objects.get(id=product_id)
    print(product)
    context = {
        "product": product
    }
    return render(request, "myapp/detail.html", context)

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>
    {% include "myapp/navbar.html" %}
    {% block content %}

    {% endblock content %}
</body>
</html>

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load static %}
{% load humanize %}
 
{% block content %}

<div class="flex p-10 w-full h-200">
    <img class="w-1/3 h-100" src="{{ product.image.url }}" alt="itemPhoto">
    <div class="w-2/3 text-xl ml-10 mt-5">
        <p class="mt-5">{{ product.name }}</p>
        <p class="mt-5 text-green-500">$ {{ product.price | intcomma }}</p>
        <p class="mt-5 text-gray-600">{{ product.description }}</p>
        {% comment %} <p class="mt-5 text-gray-600"><a href="{% url 'users:sellerprofile' item.seller.id %}">@{{ item.seller }}</a></p>
        <p class="mt-5 text-gray-600">{{ item.seller.profile.contact_number }}</p>
        <button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.id %}">Update Item</a></button>
        <button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a></button>
        <button class="bg-green-500 text-white mt-[50px]" id="checkout">Checkout</button> {% endcomment %}
    </div>
    
</div>

{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% load static %}
{% block content %}
<div class="bg-white">
    <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">Customers also purchased</h2>
        {% for product in products %}
        <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
            <div class="group relative">
              <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                <img src="{{product.image.url}}" alt="Front of men&#039;s Basic Tee in black." class="h-full w-full object-cover object-center lg:h-full lg:w-full">
              </div>
              <div class="mt-4 flex justify-between">
                <div>
                  <h3 class="text-sm text-gray-700">
                    <a href="{% url 'myapp:detail' product.id %}">
                      <span aria-hidden="true" class="absolute inset-0"></span>
                      {{product.name}}
                    </a>
                  </h3>
                  <p class="mt-1 text-sm text-gray-500">{{product.description}}</p>
                </div>
                <p class="text-sm font-medium text-gray-900">{{product.price}}</p>
              </div>
            </div>
      
            <!-- More products... -->
          </div>
        {% endfor %}
    </div>
  </div>
{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="relative flex h-16 items-center justify-between">

        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
          <div class="flex flex-shrink-0 items-center">
            <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          </div>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <a href="{% url 'myapp:home' %}" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Dashboard</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  
    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" id="mobile-menu">
      <div class="space-y-1 px-2 pb-3 pt-2">
        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
        <a href="#" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">Dashboard</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a>
      </div>
    </div>
</nav>
  